export const images = Object.freeze({
  logo: require("../assets/images/logo.png"),
  shopping: require("../assets/images/shopping.png"),
  phone: require("../assets/images/phone.png"),
  white_transparent_bg: require("../assets/images/white_trans_bg.png"),
  onboarding1: require("../assets/images/onboarding1.png"),
  onboarding2: require("../assets/images/onboarding2.png"),
  onboarding3: require("../assets/images/onboarding3.png"),
  onboarding33: require("../assets/images/onboarding33.png"),
  sound: require("../assets/images/sound.png"),
  notification: require("../assets/images/notification.png"),
  profile: require("../assets/images/user.png"),
  search: require("../assets/images/search.png"),
  filter: require("../assets/images/filter.png"),
  announcement: require("../assets/images/announce.png"),
  share: require("../assets/images/share.png"),
  clock: require("../assets/images/clock.png"),
  back: require("../assets/images/backBtn.png"),
  back_white: require("../assets/images/back_white.png"),
  dollor: require("../assets/images/dollor.png"),
  copy: require("../assets/images/clipboard.png"),
  clipboard: require("../assets/images/clipboard.png"),
  earn: require("../assets/images/earn.png"),
  link: require("../assets/images/link.png"),
  wallet: require("../assets/images/wallet.png"),
  shareIcon: require("../assets/images/shareIcon.png"),
  // Profile menu icons
  editProfile: require("../assets/images/editProfile.png"),
  paymentMethod: require("../assets/images/paymentMethod.png"),
  preferences: require("../assets/images/preferences.png"),
  referral: require("../assets/images/referral.png"),
  help: require("../assets/images/help.png"),
  transaction: require("../assets/images/transaction.png"),
  logout: require("../assets/images/logout.png"),
  rightArrow: require("../assets/images/rightArrow.png"),
  allBg: require("../assets/images/allBg.png"),
  splashBg: require("../assets/images/splashBg.png"),
  // Preferences icons
  push: require("../assets/images/push.png"),
  earning: require("../assets/images/earning.png"),
});
